import type { Metadata } from "next";
import { Borel, Caprasimo, Jua } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/Header";

const borel = Borel({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
  variable: "--font-borel",
});

const jua = Jua({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-jua",
});

const caprasimo = Caprasimo({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-caprasimo",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${borel.variable} ${jua.variable} ${caprasimo.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        {children}
      </body>
    </html>
  );
}
